Add Tests
lucas-buccilli/gym-buddy pull request #12
Opened 2023-11-15 16:59 UTC by glushkovaWT

2023-11-20 17:05 UTC, lucas-buccilli requested changes

2023-11-20 17:05 UTC, lucas-buccilli commented on src/main/java/com/example/gymbuddy/implementation/configurations/ModelMapperConfig.java
> +
Remove commented out code

2023-11-20 17:05 UTC, lucas-buccilli commented on src/main/java/com/example/gymbuddy/implementation/services/MachineService.java
> +        if(exists) throw new RuntimeException("Exists");
Create a custom exception like DuplicateEntityException

2023-11-20 17:05 UTC, lucas-buccilli commented on src/test/java/com/example/gymbuddy/implementation/controllers/MachineHistoryControllerTest.java
> +                //.andExpect(jsonPath("$.timestamp").isNotEmpty())
Remove commented out code

2023-11-20 17:05 UTC, lucas-buccilli commented on src/test/java/com/example/gymbuddy/integration/repository/MachineHistoryRepositoryIntegrationTest.java
> +    void temp2() {
Name tests in this integration test to something more specific

2023-11-20 17:10 UTC, lucas-buccilli commented on src/main/java/com/example/gymbuddy/implementation/configurations/ModelMapperConfig.java
> +//        modelMapper.
Remove commented out code

2023-11-20 17:12 UTC, glushkovaWT commented on src/main/java/com/example/gymbuddy/implementation/configurations/ModelMapperConfig.java
> +//        modelMapper.
done

2023-11-22 16:26 UTC, lucas-buccilli approved these changes

2023-11-22 16:26 UTC, merged